export const PLUGIN_DATA_KEY_PREFIX = '__VARIABLE_HISTORY__';

export const PLUGIN_DATA_KEY_SETTING = `${PLUGIN_DATA_KEY_PREFIX}SETTING`;

export const PLUGIN_DATA_KEY_HEAD = `${PLUGIN_DATA_KEY_PREFIX}HEAD`;

export const PLUGIN_DATA_KEY_COMMITS = `${PLUGIN_DATA_KEY_PREFIX}COMMITS`;

export const DISABLE_VARIABLE_NAME_PREFIX = '__ignored/';
